### ISSUE TITLE
Could not collect genesis block: StatusCodeError: 404 - undefined

### ISSUE THREAD

**Issue by t1634** [TurtlePay/blockchain-data-collection-agent#10]
Os Ubuntu 18.04 with curl -sL https://deb.nodesource.com/setup_12.x -o 
Node fully sync TurtleCoin current version
added blockchain-data-collection-agent in same directory as turtlecoin added database password and user changes checked MySQL log to make sure user was accessing okay: get this  (Got an error reading communication packets)
Updated 
[mysqld]
innodb_io_capacity = 2000
innodb_read_io_threads = 64
innodb_thread_concurrency = 0
innodb_write_io_threads = 64

innodb_buffer_pool_size =8G
and other  tweaks as suggested  << but I get this  
Thu, 15 Apr 2021 14:20:34 GMT: [ERROR] Could not collect genesis block: StatusCodeError: 404 - undefined
    at new StatusCodeError (/home/seed2/blockchain-data-collection-agent/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/seed2/blockchain-data-collection-agent/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/seed2/blockchain-data-collection-agent/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/seed2/blockchain-data-collection-agent/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/seed2/blockchain-data-collection-agent/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/seed2/blockchain-data-collection-agent/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22) {
  statusCode: 404,
  error: undefined,
  options: [Object],
  response: [IncomingMessage]
}
It all seems to be installed correctly Node is currently  2021-Apr-15 16:59:50.684677 INFO    New Top Block Detected: 3499963
2021-Apr-15 17:00:08.945435 INFO    New Top Block Detected: 3499964
2021-Apr-15 17:01:56.208903 INFO    New Top Block Detected: 3499965
2021-Apr-15 17:02:01.029048 INFO    New Top Block Detected: 3499966
2021-Apr-15 17:02:22.637069 INFO    New Top Block Detected: 3499967

if you could give me any help or suggestions it would be great

**Comment by brandonlehmann** [comment]
This software does not work with the the TurtleCoind v1 API. It will not be able to collect blocks and cache the information without considerable upgrades to the software. Unfortunately, with v2 on the way, this will not be fixed.

**Comment by t1634** [comment]
Oh thank you
